name: remind_clone
description: Real Remind.com clone
version: 1.0.0
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0
  firebase_messaging: ^15.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  uuid: ^4.5.0
  google_fonts: ^6.2.0

flutter:
  uses-material-design: true
